SELECT
 "SALDOS"."REGIONAL OFICINA" AS "REGIONAL OFICINA",
  "SALDOS"."CODIGO OFICINA" AS "CODIGO OFICINA",
  "TRANS"."OFICINA GENERADORA" AS "OFICINA GENERADORA",
  "TRANS"."NUMERO CHEQUE GERENCIA" AS "NUMERO CHEQUE GERENCIA",
  "TRANS"."NOMBRE BENEFICIARIO CHEQUE" AS "NOMBRE BENEFICIARIO CHEQUE",
  "TRANS"."TIPO IDENTIFICACION BENEFICIARIO" AS "TIPO IDENTIFICACION BENEFICIARIO",
  "TRANS"."NUMERO IDENTIFICACION BENEFICIARIO" AS "NUMERO IDENTIFICACION BENEFICIARIO",
  "TRANS"."FECHA EXPEDICION CHEQUE GERENCIA" AS "FECHA EXPEDICION CHEQUE GERENCIA",
  "TRANS"."FECHA OPERACION CHEQUE" AS "FECHA OPERACION CHEQUE",
  "TRANS"."ESTADO CHEQUE GERENCIA" AS "ESTADO CHEQUE GERENCIA",
  "TRANS"."NATURALEZA TRANSACCION" AS "NATURALEZA TRANSACCION",
  "TRANS"."UBICACION CHEQUE" AS "UBICACION CHEQUE",
  "TRANS"."FECHA_PAGO" AS "FECHA_PAGO",
  "TRANS"."FECHA_INACTIVA" AS "FECHA_INACTIVA",
  "TRANS"."FECHA_CANCELACION" AS "FECHA_CANCELACION",
  "TRANS"."VALOR CHEQUE" AS "VALOR CHEQUE",
  "SALDOS"."SALDO CR INICIO DIA"  AS "SALDO CR INICIO DIA",
  "TRANS"."DEBITO" AS "DEBITO",
  "TRANS"."CREDITO" AS "CREDITO",
  "TRANS"."CONJUNCION" AS "CONJUNCION",
  "TRANS"."NOMBRE BENEFICIARIO 2" AS "NOMBRE BENEFICIARIO 2",
  "TRANS"."NOMBRE BENEFICIARIO 3" AS "NOMBRE BENEFICIARIO 3",
  "TRANS"."NUMERO IDENTIFICACION 2" AS "NUMERO IDENTIFICACION 2",
  "TRANS"."NUMERO IDENTIFICACION 3" AS "NUMERO IDENTIFICACION 3",
  "TRANS"."TIPO IDENTIFICACION 2" AS "TIPO IDENTIFICACION 2",
  "TRANS"."TIPO IDENTIFICACION 3" AS "TIPO IDENTIFICACION 3",
  "TRANS"."UBICACION_DEL_CHEQUE" AS "UBICACION DEL CHEQUE"
  
FROM
(SELECT  
 "VALORES UDF CHEQUES GERENCIA"."CONJUNCION" AS "CONJUNCION",
  "VALORES UDF CHEQUES GERENCIA"."NOMBRE BENEFICIARIO 2" AS "NOMBRE BENEFICIARIO 2",
  "VALORES UDF CHEQUES GERENCIA"."NOMBRE BENEFICIARIO 3" AS "NOMBRE BENEFICIARIO 3",
  "VALORES UDF CHEQUES GERENCIA"."NUMERO IDENTIFICACION 2" AS "NUMERO IDENTIFICACION 2",
  "VALORES UDF CHEQUES GERENCIA"."NUMERO IDENTIFICACION 3" AS "NUMERO IDENTIFICACION 3",
  "VALORES UDF CHEQUES GERENCIA"."TIPO IDENTIFICACION 2" AS "TIPO IDENTIFICACION 2",
  "VALORES UDF CHEQUES GERENCIA"."TIPO IDENTIFICACION 3" AS "TIPO IDENTIFICACION 3",
 "TRANSACCIONES CHEQUES GERENCIA"."OFICINA GENERADORA" AS "OFICINA GENERADORA",
  "TRANSACCIONES CHEQUES GERENCIA"."NUMERO CHEQUE GERENCIA" AS "NUMERO CHEQUE GERENCIA",
  "TRANSACCIONES CHEQUES GERENCIA"."NOMBRE BENEFICIARIO CHEQUE" AS "NOMBRE BENEFICIARIO CHEQUE",
  "TRANSACCIONES CHEQUES GERENCIA"."TIPO IDENTIFICACION BENEFICIARIO" AS "TIPO IDENTIFICACION BENEFICIARIO",
  "TRANSACCIONES CHEQUES GERENCIA"."NUMERO IDENTIFICACION BENEFICIARIO" AS "NUMERO IDENTIFICACION BENEFICIARIO",
  "TRANSACCIONES CHEQUES GERENCIA"."FECHA EXPEDICION CHEQUE GERENCIA" AS "FECHA EXPEDICION CHEQUE GERENCIA",
  "TRANSACCIONES CHEQUES GERENCIA"."FECHA OPERACION CHEQUE" AS "FECHA OPERACION CHEQUE",
  "TRANSACCIONES CHEQUES GERENCIA"."ESTADO CHEQUE GERENCIA" AS "ESTADO CHEQUE GERENCIA",
  "MANTENIMIENTO PRODUCTOS FC"."NATURALEZA TRANSACCION" AS "NATURALEZA TRANSACCION",
  "TRANSACCIONES CHEQUES GERENCIA"."UBICACION CHEQUE" AS "UBICACION CHEQUE",
  "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE" AS "VALOR CHEQUE",
  CASE "TRANSACCIONES CHEQUES GERENCIA"."ESTADO CHEQUE GERENCIA" WHEN 'LIQD' THEN "TRANSACCIONES CHEQUES GERENCIA"."FECHA OPERACION CHEQUE" END AS "FECHA_PAGO",
  CASE "TRANSACCIONES CHEQUES GERENCIA"."ESTADO CHEQUE GERENCIA" WHEN 'INAV' THEN "TRANSACCIONES CHEQUES GERENCIA"."FECHA OPERACION CHEQUE" END AS "FECHA_INACTIVA",
  CASE "TRANSACCIONES CHEQUES GERENCIA"."ESTADO CHEQUE GERENCIA" WHEN 'CNCL' THEN "TRANSACCIONES CHEQUES GERENCIA"."FECHA OPERACION CHEQUE" END AS "FECHA_CANCELACION",
  
  CASE WHEN "TRANSACCIONES CHEQUES GERENCIA"."FECHA EXPEDICION CHEQUE GERENCIA" = "TRANSACCIONES CHEQUES GERENCIA"."FECHA OPERACION CHEQUE"THEN
                 CASE "TRANSACCIONES CHEQUES GERENCIA"."ESTADO CHEQUE GERENCIA" WHEN 'RISF' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'CLBK' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'CNCL' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'LIQD' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'RISF' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'RISR' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'INIT' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'INAV' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'DISU' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  ELSE 0 END
  
  WHEN "TRANSACCIONES CHEQUES GERENCIA"."FECHA EXPEDICION CHEQUE GERENCIA" < "TRANSACCIONES CHEQUES GERENCIA"."FECHA OPERACION CHEQUE" THEN
                 CASE "TRANSACCIONES CHEQUES GERENCIA"."ESTADO CHEQUE GERENCIA" WHEN 'RISF' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'INIT' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'RISF' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'RISR' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'RISV' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  WHEN 'DISU' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                                  ELSE 0 END
                                  ELSE 0 END AS "CREDITO",
                 
  CASE "TRANSACCIONES CHEQUES GERENCIA"."ESTADO CHEQUE GERENCIA" WHEN 'CLBK' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                WHEN 'CNCL' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                WHEN 'LIQD' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                WHEN 'INAV' THEN "TRANSACCIONES CHEQUES GERENCIA"."VALOR CHEQUE"
                ELSE 0 END  AS "DEBITO",
                                  
  CASE "TRANSACCIONES CHEQUES GERENCIA"."UBICACION CHEQUE" WHEN 'B' THEN 'BANCO'
                WHEN 'C' THEN 'CLIENTE'
                ELSE ''
                END AS "UBICACION_DEL_CHEQUE"
 
 
 FROM "CBS - PRODUCTOS PASIVAS"."MANTENIMIENTO PRODUCTOS FC" "MANTENIMIENTO PRODUCTOS FC",
 "CBS - PRODUCTOS PASIVAS"."TRANSACCIONES CHEQUES GERENCIA" "TRANSACCIONES CHEQUES GERENCIA",
 "CBS - PRODUCTOS PASIVAS"."VALORES UDF CHEQUES GERENCIA" "VALORES UDF CHEQUES GERENCIA") AS "TRANS"

INNER JOIN


 (SELECT "SALDOS CONTABLES"."OFICINA  CUENTA CONTABLE" AS "OFICINA  CUENTA CONTABLE",
   "SALDOS CONTABLES"."AÑO" AS "AÑO",
   "SALDOS CONTABLES"."CUENTA CONTABLE" AS "CUENTA CONTABLE",
   "SALDOS CONTABLES"."SALDO CR INICIO DIA" AS "SALDO CR INICIO DIA",
   "SALDOS CONTABLES"."PERIODO" AS "PERIODO",
   --CAST(YEAR(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE))-2 AS CHAR) AS "AÑIO",
   --CASE WHEN LENGTH (CAST(MONTH(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE)) -8 AS CHAR))= 1
   --  THEN '0'|| CAST(MONTH(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE)) -8 AS CHAR)
   --  ELSE CAST(MONTH(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE)) AS CHAR) END   AS "MES",
   --CAST(SUBSTRING(CAST(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE) AS CHAR) FROM 0 FOR 9) AS DATE) AS "MES_PRUEBA",
   --SUBSTRING("SALDOS CONTABLES"."PERIODO",2,3) AS "MONTHS",
   --SUBSTRING("SALDOS CONTABLES"."AÑO",3,6) AS "YEARS",
   "OFICINAS FC"."REGIONAL OFICINA" AS "REGIONAL OFICINA",
   "OFICINAS FC"."CODIGO OFICINA" AS "CODIGO OFICINA",
   TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE) AS "DIA DE HOY"
     
 FROM "CBS - PRODUCTOS PASIVAS"."SALDOS CONTABLES" "SALDOS CONTABLES",
  "CBS - PRODUCTOS PASIVAS"."OFICINAS FC" "OFICINAS FC"
 WHERE CAST(YEAR(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE)) AS CHAR) = CAST(SUBSTRING("SALDOS CONTABLES"."AÑO",3,6)  AS CHAR)
 AND
   CASE WHEN LENGTH (CAST(MONTH(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE)) AS CHAR))= 1
     THEN '0'|| CAST(MONTH(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE)) AS CHAR)
     ELSE CAST(MONTH(TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE)) AS CHAR) END = CAST(SUBSTRING("SALDOS CONTABLES"."PERIODO",2,3) AS CHAR) AND
     
   
   --"SALDOS CONTABLES"."AÑO" LIKE '%2011' AND
   --"SALDOS CONTABLES"."PERIODO" LIKE '%S01' AND
   "SALDOS CONTABLES"."CUENTA CONTABLE" = '21651501' 
   AND "SALDOS CONTABLES"."OFICINA  CUENTA CONTABLE" IN (:P_OFICINA)
   ) "SALDOS"
   
ON "SALDOS"."OFICINA  CUENTA CONTABLE" = "TRANS"."OFICINA GENERADORA"
WHERE "SALDOS"."REGIONAL OFICINA" IN (:P_REGIONAL) AND
"TRANS"."FECHA OPERACION CHEQUE" = TIMESTAMPADD(SQL_TSI_DAY,0,CURRENT_DATE)
-----------